language: objective-c
cache: cocoapods
podfile: Example/Podfile
osx_image: xcode7
before_install:
 - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/BleCommC.xcworkspace -scheme BleCommC-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
